#!/bin/bash
#
# generate-secrets.sh
# Generates Secrets.swift from environment variables.
# Use in CI/CD or local setup.
#
# Required env vars:
#   GOOGLE_GEMINI_API_KEY
#
# Note: OpenFoodFacts API doesn't require an API key
#

set -euo pipefail

OUTPUT="CountMe/Utilities/Secrets.swift"

# Validate required env vars
missing=()
[ -z "${GOOGLE_GEMINI_API_KEY:-}" ] && missing+=("GOOGLE_GEMINI_API_KEY")

if [ ${#missing[@]} -ne 0 ]; then
    echo "❌ Missing required environment variables: ${missing[*]}"
    echo "   Set them before running this script, or copy Secrets.swift.template manually."
    exit 1
fi

cat > "$OUTPUT" << EOF
//
//  Secrets.swift
//  CountMe
//
//  AUTO-GENERATED by generate-secrets.sh — DO NOT EDIT OR COMMIT
//

import Foundation

enum Secrets {
    // OpenFoodFacts API doesn't require an API key - it's free and open!
    // Just need to provide a User-Agent header in requests
    
    static let googleGeminiAPIKey = "${GOOGLE_GEMINI_API_KEY}"
}
EOF

echo "✅ Generated $OUTPUT"
